### 1. server info
id: 57bc97b7-50d2-4d87-a0bf-511221ca468c    # device ID
ip: 192.168.0.109    # device IP address

### 2. filestore info
performance: true    # device performance: true for "high", or false for "low"
mem: 10               # prepared storage memory for OpenRaaS
bw: 1000    # mbps
latency: 1  # ms

### 3. file-sharing info
fs_protocol: davfs  # protocol name (WebDav is "davfs")
fs_directory: "/"   # the directory of target files for mounting
fs_port: 10950    # file_sharing port
fs_user: kb109    # user
fs_pwd: 123456    # password